### ISSUE TITLE
Remove reactstrap and bootstrap?

### ISSUE THREAD

**Issue by davelab6** [SorkinType/EQX#114]
@quitequinn the README says,

    # To Do
    Remove reactstrap and bootstrap

Is that done, so readme can be updated, or still to do? :)

**Comment by quitequinn** [comment]
Can definitely be removed, but there is a lot of house cleaning of components still to do aswell.

**Comment by quitequinn** [comment]
oops that's in the readme!

**Comment by davelab6** [comment]
Maybe better to track TODOs here as issues?
